// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDWE_zWzJS2jyhqJ3XNJEIvBzjlw9Cv2Jk',
    appId: '1:442344968402:web:568514b958606c69139d0b',
    messagingSenderId: '442344968402',
    projectId: 'inway212',
    authDomain: 'inway212.firebaseapp.com',
    storageBucket: 'inway212.appspot.com',
    measurementId: 'G-T0068GSTJW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDDNvPcUVdNMPKYqZ6fEi0ffAJO_ioy2gM',
    appId: '1:442344968402:android:90d0be6a69581b1f139d0b',
    messagingSenderId: '442344968402',
    projectId: 'inway212',
    storageBucket: 'inway212.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAAxT8DN6GxvHYxgx5ilMs_hY75BepoUFo',
    appId: '1:442344968402:ios:c4807167fe496fa3139d0b',
    messagingSenderId: '442344968402',
    projectId: 'inway212',
    storageBucket: 'inway212.appspot.com',
    androidClientId: '442344968402-2jgfc78dclji973bpokgqspmabo2nurq.apps.googleusercontent.com',
    iosClientId: '442344968402-v7rg27f4ujn93fiojp1807u7termka9l.apps.googleusercontent.com',
    iosBundleId: 'com.project.inway.inway',
  );
}
